version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: sinister-nextpvr_server_1
      APP_PORT: 8867
      PROXY_AUTH_ADD: "false"

  server:
    image: nextpvr/nextpvr_amd64:stable
    restart: on-failure
    hostname: "${DEVICE_HOSTNAME}"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads/videos:/recordings
      - ${UMBREL_ROOT}/data/storage/downloads/videos:/buffer