version: '3.7'

services:
  crafty:
    container_name: sinister-crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: unless-stopped
    environment:
        - TZ=Europe/London
    ports:
        - "8500:8000" # HTTP
        - "8543:8443" # HTTPS
        - "8523:8123" # DYNMAP
        - "19132:19132/udp" # BEDROCK
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - ${APP_DATA_DIR}/backups:/crafty/backups
        - ${APP_DATA_DIR}/logs:/crafty/logs
        - ${APP_DATA_DIR}/servers:/crafty/servers
        - ${APP_DATA_DIR}/config:/crafty/app/config
        - ${APP_DATA_DIR}/import:/crafty/import