version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: sinister-crafty_server_1
      APP_PORT: 8443
      PROXY_AUTH_ADD: "false"

  server:
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
        - TZ=Europe/London
    ports:
        - "8123:8123" # DYNMAP
        - "19132:19132/udp" # BEDROCK
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - ${APP_DATA_DIR}/backups:/crafty/backups
        - ${APP_DATA_DIR}/logs:/crafty/logs
        - ${APP_DATA_DIR}/servers:/crafty/servers
        - ${APP_DATA_DIR}/config:/crafty/app/config
        - ${APP_DATA_DIR}/import:/crafty/import